<?php

use App\Modules\Identity\Presentation\Http\Controllers\PublicUserProfileController;
use Illuminate\Support\Facades\Route;

// Compatibility routes for the organizer participation role introduced by task 191.
// The canonical URL is still generated by users.role/users.id.role; these routes only
// extend inbound matching without rewriting the large legacy web route file.
Route::get('/users/id/{user}/organizer', [PublicUserProfileController::class, 'show'])
    ->whereNumber('user')
    ->defaults('by_id', true)
    ->defaults('role', 'organizer');

Route::get('/users/{user:username}/organizer', [PublicUserProfileController::class, 'show'])
    ->defaults('role', 'organizer');
