@php($editing = $section !== null)
@extends('theme::layouts.section-sidebar', [
    'title' => $editing ? 'Секция · '.$section->name : 'Новая секция', 'sectionId' => 'account', 'sectionClass' => 'account-section',
    'contentTitle' => $editing ? $section->name : 'Новая секция', 'sidebarLabel' => 'Навигация аккаунта',
    'wrapSidebarPanel' => false, 'sidebarPartial' => 'theme::partials.account.sidebar',
])

@section('section-content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="sports-section-editor">
<section class="sports-section-editor__panel"><h2>Основное</h2>
<form method="POST" action="{{ $editing ? route('account.sports-sections.update', $section) : route('account.sports-sections.store') }}" class="sports-section-form">@csrf @if($editing)@method('PUT')@endif
    <label class="form-field"><span>Название</span><input class="form-control" name="name" required value="{{ old('name', $section?->name) }}"></label>
    <label class="form-field sports-section-form__wide"><span>Описание</span><textarea class="form-control" name="description" rows="4">{{ old('description', $section?->description) }}</textarea></label>
    @if($editing)<label class="form-field"><span>Статус</span><select class="form-select" name="status">@foreach($statuses as $item)<option value="{{ $item->value }}" @selected(old('status', $section->status->value) === $item->value)>{{ $item->label() }}</option>@endforeach</select></label>@endif
    <label class="form-field"><span>Формат тренировок</span><select class="form-select" name="training_mode">@foreach($trainingModes as $item)<option value="{{ $item->value }}" @selected(old('training_mode', $section?->training_mode?->value) === $item->value)>{{ $item->label() }}</option>@endforeach</select></label>
    <label class="form-field"><span>Игровой формат</span><select class="form-select" name="game_format">@foreach($formats as $item)<option value="{{ $item->value }}" @selected(old('game_format', $section?->game_format?->value ?? 'basketball_5x5') === $item->value)>{{ $item->label() }}</option>@endforeach</select></label>
    <label class="form-field"><span>Основная площадка</span><select class="form-select" name="primary_venue_id"><option value="">Не указана</option>@foreach($venues as $venue)<option value="{{ $venue->id }}" @selected((string)old('primary_venue_id', $section?->primary_venue_id) === (string)$venue->id)>{{ $venue->name }}</option>@endforeach</select></label>
    <label class="form-field"><span>Основной зал</span><select class="form-select" name="primary_venue_court_id"><option value="">Не указан</option>@foreach($venues as $venue)@foreach($venue->courts as $court)<option value="{{ $court->id }}" @selected((string)old('primary_venue_court_id', $section?->primary_venue_court_id) === (string)$court->id)>{{ $venue->name }} — {{ $court->name }}</option>@endforeach @endforeach</select></label>
    <label class="form-field"><span>Оплата</span><select class="form-select" name="pricing_type">@foreach($pricingTypes as $item)<option value="{{ $item->value }}" @selected(old('pricing_type', $section?->pricing_type?->value ?? 'free') === $item->value)>{{ $item->label() }}</option>@endforeach</select></label>
    <label class="form-field"><span>Стоимость занятия, руб.</span><input class="form-control" type="number" min="0" step="0.01" name="single_session_price" value="{{ old('single_session_price', $section?->single_session_price_minor !== null ? $section->single_session_price_minor / 100 : '') }}"></label>
    <input type="hidden" name="currency" value="RUB">
    <label class="form-field"><span>Источник контактов</span><select class="form-select" name="contact_source">@foreach($contactSources as $item)<option value="{{ $item->value }}" @selected(old('contact_source', $section?->contact_source?->value ?? 'head_coach') === $item->value)>{{ $item->label() }}</option>@endforeach</select></label>
    <label class="form-field"><span>Примечание к контактам</span><input class="form-control" name="contact_notes" value="{{ old('contact_notes', $section?->contact_notes) }}"></label>
    <div class="sports-section-form__wide"><button class="btn btn--primary" type="submit">{{ $editing ? 'Сохранить' : 'Создать секцию' }}</button></div>
</form></section>

@if($editing)
<section class="sports-section-editor__panel"><h2>Фотографии</h2><div class="sports-section-editor__gallery">@foreach($section->media as $photo)<article><img src="{{ $photo->publicUrl() }}" alt=""><div>@if(!$photo->is_featured)<form method="POST" action="{{ route('account.sports-sections.photos.feature', [$section, $photo->id]) }}">@csrf @method('PATCH')<button class="btn btn--secondary btn--sm">Сделать основной</button></form>@else<span class="text-accent">Основная</span>@endif<form method="POST" action="{{ route('account.sports-sections.photos.destroy', [$section, $photo->id]) }}">@csrf @method('DELETE')<button class="btn btn--secondary btn--sm">Удалить</button></form></div></article>@endforeach</div><form method="POST" enctype="multipart/form-data" action="{{ route('account.sports-sections.photos.store', $section) }}">@csrf<input class="form-control" type="file" name="photo" accept="image/jpeg,image/png,image/webp" required><button class="btn btn--primary btn--sm">Добавить фото</button></form></section>

<section class="sports-section-editor__panel"><h2>Тренеры</h2><div class="sports-section-editor__items">@foreach($section->coachMemberships as $membership)@php($name = trim(($membership->user?->profile?->first_name ?? '').' '.($membership->user?->profile?->last_name ?? '')) ?: $membership->user?->username)<article><strong>{{ $name }}</strong><span>{{ $section->head_coach_membership_id === $membership->id ? 'Главный тренер' : 'Тренер' }}</span>@if($membership->access_level !== 'owner')<details><summary>Права</summary><form method="POST" action="{{ route('account.sports-sections.coaches.permissions', [$section, $membership]) }}">@csrf @method('PUT')@foreach(\App\Modules\SportsSection\Domain\Enums\SportsSectionPermissionEnum::cases() as $permission)<label><input type="checkbox" name="permissions[]" value="{{ $permission->value }}" @checked($membership->contract->permissions->contains('permission', $permission->value))> {{ $permission->label() }}</label>@endforeach<button class="btn btn--secondary btn--sm">Сохранить права</button></form></details>@endif @if($section->head_coach_membership_id !== $membership->id)<div><form method="POST" action="{{ route('account.sports-sections.coaches.head-coach', [$section, $membership]) }}">@csrf @method('PATCH')<button class="btn btn--secondary btn--sm">Назначить главным</button></form><form method="POST" action="{{ route('account.sports-sections.coaches.destroy', [$section, $membership]) }}">@csrf @method('DELETE')<button class="btn btn--secondary btn--sm">Отключить</button></form></div>@endif</article>@endforeach</div><form method="POST" action="{{ route('account.sports-sections.coaches.store', $section) }}" class="sports-section-editor__inline">@csrf @include('theme::partials.forms.entity-predictive-search', ['id' => 'sportsSectionCoach', 'name' => 'user_id', 'label' => 'Подтверждённый тренер', 'placeholder' => 'Имя или логин…', 'searchUrl' => route('account.sports-sections.candidates', [$section, 'role' => 'coach'])])<button class="btn btn--primary btn--sm">Добавить тренера</button></form></section>

<section class="sports-section-editor__panel"><h2>Тренируемые</h2><div class="sports-section-editor__items">@foreach($section->traineeMemberships as $membership)<article><strong>{{ trim(($membership->user?->profile?->first_name ?? '').' '.($membership->user?->profile?->last_name ?? '')) ?: $membership->user?->username }}</strong><span>{{ $membership->status->label() }}</span>@if($membership->status->value === 'active')<form method="POST" action="{{ route('account.sports-sections.trainees.deactivate', [$section, $membership]) }}">@csrf @method('PATCH')<input class="form-control" name="reason" placeholder="Причина, необязательно"><button class="btn btn--secondary btn--sm">В неактивные</button></form>@endif</article>@endforeach</div><form method="POST" action="{{ route('account.sports-sections.trainees.store', $section) }}" class="sports-section-editor__inline">@csrf @include('theme::partials.forms.entity-predictive-search', ['id' => 'sportsSectionPlayer', 'name' => 'user_id', 'label' => 'Подтверждённый игрок', 'placeholder' => 'Имя или логин…', 'searchUrl' => route('account.sports-sections.candidates', [$section, 'role' => 'player'])])<button class="btn btn--primary btn--sm">Добавить</button></form></section>

<section class="sports-section-editor__panel"><h2>Тарифы</h2><div class="sports-section-editor__items">@foreach($section->pricingPlans as $plan)<article><strong>{{ $plan->name }}</strong><span>{{ number_format($plan->amount_minor / 100, 0, ',', ' ') }} руб. · {{ $plan->is_active ? 'Активен' : 'Выключен' }}</span><form method="POST" action="{{ route('account.sports-sections.plans.toggle', [$section, $plan]) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $plan->is_active ? 0 : 1 }}"><button class="btn btn--secondary btn--sm">{{ $plan->is_active ? 'Выключить' : 'Включить' }}</button></form></article>@endforeach</div><form method="POST" action="{{ route('account.sports-sections.plans.store', $section) }}" class="sports-section-editor__inline">@csrf<input class="form-control" name="name" placeholder="Название" required><input class="form-control" name="amount" type="number" min="0.01" step="0.01" placeholder="Цена, руб." required><input class="form-control" name="sessions_count" type="number" min="1" placeholder="Занятий"><input class="form-control" name="duration_days" type="number" min="1" placeholder="Дней"><button class="btn btn--primary btn--sm">Добавить тариф</button></form></section>

<section class="sports-section-editor__panel"><h2>Контакты секции</h2><div class="sports-section-editor__items">@foreach($section->contacts as $contact)<article><strong>{{ $contact->type->label() }}</strong><span>{{ $contact->displayValue() }}</span><form method="POST" action="{{ route('account.sports-sections.contacts.destroy', [$section, $contact]) }}">@csrf @method('DELETE')<button class="btn btn--secondary btn--sm">Удалить</button></form></article>@endforeach</div><form method="POST" action="{{ route('account.sports-sections.contacts.store', $section) }}" class="sports-section-editor__inline">@csrf<select class="form-select" name="type">@foreach(\App\Modules\Contact\Domain\Enums\ContactTypeEnum::cases() as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select><input class="form-control" name="value" required placeholder="Значение"><input class="form-control" name="label" placeholder="Подпись"><button class="btn btn--primary btn--sm">Добавить</button></form></section>

<section class="sports-section-editor__panel"><h2>Занятия</h2>
    <form method="POST" action="{{ route('account.sports-sections.sessions.store', $section) }}" class="sports-section-editor__inline">@csrf
        <input class="form-control" type="datetime-local" name="starts_at" required><input class="form-control" type="datetime-local" name="ends_at" required>
        <select class="form-select" name="venue_id"><option value="">Место секции</option>@foreach($venues as $venue)<option value="{{ $venue->id }}">{{ $venue->name }}</option>@endforeach</select>
        <select class="form-select" name="venue_court_id"><option value="">Зал секции</option>@foreach($venues as $venue)@foreach($venue->courts as $court)<option value="{{ $court->id }}">{{ $venue->name }} — {{ $court->name }}</option>@endforeach @endforeach</select>
        <input class="form-control" name="price_override" type="number" min="0" step="0.01" placeholder="Другая цена, руб."><button class="btn btn--primary btn--sm">Создать</button>
    </form>
    <div class="sports-section-editor__sessions">
    @foreach($section->trainingSessions as $session)
        <article><header><strong>{{ $session->starts_at->format('d.m.Y H:i') }}–{{ $session->ends_at->format('H:i') }}</strong><span>{{ $session->status->label() }} · {{ $session->participants->count() }} участников · {{ $session->coaches->count() }} тренеров</span></header>
            <details><summary>Snapshot состава</summary>
                <div class="sports-section-editor__snapshot"><strong>Участники</strong>@foreach($session->participants as $participant)<form method="POST" action="{{ route('account.sports-sections.sessions.participants.destroy', [$section, $session, $participant->id]) }}">@csrf @method('DELETE')<span>{{ $participant->user?->username }}</span><button class="btn btn--secondary btn--sm">Убрать</button></form>@endforeach
                    <form method="POST" action="{{ route('account.sports-sections.sessions.participants.store', [$section, $session]) }}">@csrf<select class="form-select" name="user_id">@foreach($section->traineeMemberships->filter(fn ($item) => $item->status->value === 'active') as $trainee)<option value="{{ $trainee->user_id }}">{{ $trainee->user?->username }}</option>@endforeach</select><button class="btn btn--secondary btn--sm">Добавить</button></form>
                    <strong>Тренеры</strong>@foreach($session->coaches as $coach)<form method="POST" action="{{ route('account.sports-sections.sessions.coaches.destroy', [$section, $session, $coach->id]) }}">@csrf @method('DELETE')<span>{{ $coach->user?->username }}</span><button class="btn btn--secondary btn--sm">Убрать</button></form>@endforeach
                    <form method="POST" action="{{ route('account.sports-sections.sessions.coaches.store', [$section, $session]) }}">@csrf<select class="form-select" name="membership_id">@foreach($section->coachMemberships as $coachMembership)<option value="{{ $coachMembership->id }}">{{ $coachMembership->user?->username }}</option>@endforeach</select><button class="btn btn--secondary btn--sm">Добавить</button></form>
                </div>
            </details>
            @unless($session->event_id)<form method="POST" action="{{ route('account.sports-sections.sessions.event', [$section, $session]) }}">@csrf<input class="form-control" type="number" name="event_id" placeholder="ID Event типа «Тренировка»" required><button class="btn btn--secondary btn--sm">Связать с Event</button></form>@else<a href="{{ route('events.show', $session->event) }}">Открыть Event</a>@endunless
            @if($session->status->value === 'planned')<form method="POST" action="{{ route('account.sports-sections.sessions.transition', [$section, $session]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="confirmed"><button class="btn btn--primary btn--sm">Подтвердить</button></form>@endif
            @if($session->status->value === 'confirmed')<form method="POST" action="{{ route('account.sports-sections.sessions.transition', [$section, $session]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="completed"><button class="btn btn--primary btn--sm">Завершить</button></form>@endif
            @if(in_array($session->status->value, ['planned','confirmed']))<form method="POST" action="{{ route('account.sports-sections.sessions.transition', [$section, $session]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="cancelled"><input class="form-control" name="reason" required placeholder="Причина отмены"><button class="btn btn--secondary btn--sm">Отменить</button></form>@endif
        </article>
    @endforeach
    </div>
</section>
@endif
</div>
@endsection
